server:
  port: 8090

spring:
  application:
    name: blog-query-service

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/blog_read_db}
      auto-index-creation: false   # read-only service; don't create indexes

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: INFO