package com.learningpurpose.notificationservice.service.impl;

import com.learningpurpose.notificationservice.service.EmailService;
import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
@Slf4j
public class EmailServiceImpl implements EmailService{

    private final JavaMailSender mailSender;

    @Override
    public void sendWelcomeEmail(String toEmail, String name) {
        String htmlBody = """
            <div style="font-family: Arial, sans-serif; padding: 20px; background-color: #f4f4f4;">
                <div style="max-width: 600px; margin: auto; background: white; padding: 30px; border-radius: 8px;">
                    <h2 style="color: #2b5876;">Welcome to Learning Purpose, %s!</h2>
                    <p style="color: #555; line-height: 1.6;">
                        Your account registration was successful. You can now access all quizzes, courses, and educational materials.
                    </p>
                    <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
                    <p style="font-size: 12px; color: #999;">Learning Purpose Platform &copy; 2026</p>
                </div>
            </div>
            """.formatted(name != null ? name : "Learner");

        sendHtmlMail(toEmail, "Welcome to Learning Purpose Platform", htmlBody);
    }

    @Override
    public void sendOtpEmail(String toEmail, String otp) {
        String htmlBody = """
            <div style="font-family: Arial, sans-serif; padding: 20px; background-color: #f4f4f4;">
                <div style="max-width: 600px; margin: auto; background: white; padding: 30px; border-radius: 8px;">
                    <h2 style="color: #e65c00;">Password Reset Request</h2>
                    <p style="color: #555; line-height: 1.6;">Use the one-time password below to reset your account credentials:</p>
                    <div style="text-align: center; margin: 25px 0;">
                        <span style="font-size: 28px; font-weight: bold; letter-spacing: 5px; background: #fff3e6; padding: 10px 20px; border: 1px dashed #e65c00; border-radius: 4px; color: #e65c00;">
                            %s
                        </span>
                    </div>
                    <p style="color: #777; font-size: 13px;">This verification code is valid for 10 minutes. If you did not initiate this request, please disregard this email.</p>
                </div>
            </div>
            """.formatted(otp);

        sendHtmlMail(toEmail, "Learning Purpose: Password Reset Verification Code", htmlBody);
    }

    @Override
    public void sendExamResultEmail(String toEmail, String username, String quizTitle, double marks, double maxMarks, boolean passed) {
        String statusColor = passed ? "#28a745" : "#dc3545";
        String statusLabel = passed ? "PASSED" : "FAILED";

        String htmlBody = """
            <div style="font-family: Arial, sans-serif; padding: 20px; background-color: #f4f4f4;">
                <div style="max-width: 600px; margin: auto; background: white; padding: 30px; border-radius: 8px;">
                    <h2 style="color: #333;">Assessment Result: %s</h2>
                    <p style="color: #555;">Hello <strong>%s</strong>,</p>
                    <p style="color: #555;">Your quiz submission has been processed:</p>
                    <table style="width: 100%%; border-collapse: collapse; margin: 20px 0;">
                        <tr>
                            <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Status</td>
                            <td style="padding: 10px; border: 1px solid #ddd; color: %s; font-weight: bold;">%s</td>
                        </tr>
                        <tr>
                            <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Score</td>
                            <td style="padding: 10px; border: 1px solid #ddd;">%.2f / %.2f</td>
                        </tr>
                    </table>
                    <p style="font-size: 12px; color: #999;">Automated evaluation report generated by Exam Service Engine.</p>
                </div>
            </div>
            """.formatted(quizTitle, username, statusColor, statusLabel, marks, maxMarks);

        sendHtmlMail(toEmail, "Exam Performance Summary: " + quizTitle, htmlBody);
    }

    private void sendHtmlMail(String to, String subject, String htmlContent) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");
            helper.setFrom("ehsanulkhaliq274@gmail.com");
            helper.setTo(to);
            helper.setSubject(subject);
            helper.setText(htmlContent, true);
            mailSender.send(message);
            log.info("Email dispatched successfully to: {}", to);
        } catch (MessagingException e) {
            log.error("Failed to dispatch email to {}: {}", to, e.getMessage());
        }
    }
}

