input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  mutate {
    add_field => { "environment" => "development" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs-microservices-%{+YYYY.MM.dd}"
  }
  # Uncomment the line below if you want to inspect incoming logs directly in docker logs logstash
  # stdout { codec => rubydebug }
}